# Cloud Build Configuration for the loan-sheet-app service
# Version: 2.3 - Simplified without cache for reliability

steps:
  # STEP 1: Build the Spring Boot application using Maven with Java 21.
  - name: 'maven:3.9.8-eclipse-temurin-21'
    id: 'Build-Application'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Java Version ===" && \
        java -version && \
        echo "=== Maven Version ===" && \
        mvn -version && \
        echo "=== Building Application ===" && \
        mvn clean package -DskipTests=true -B
    waitFor: ['-']

  # STEP 2: Prepare the deployment artifacts in a clean staging directory.
  - name: 'alpine'
    id: 'Prepare-Deployment-Directory'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        mkdir -p deploy-stage && \
        cp src/main/appengine/app.yaml deploy-stage/ && \
        cp target/*.jar deploy-stage/application.jar && \
        echo "Deployment artifacts prepared:" && \
        ls -la deploy-stage/
    waitFor:
      - 'Build-Application'

  # STEP 3: Deploy the application to App Engine.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy-to-App-Engine'
    args:
      - 'app'
      - 'deploy'
      - 'deploy-stage/app.yaml'
      - '--promote'
      - '--quiet'
      - '--stop-previous-version'
      - '--version=${_SERVICE_NAME}-${SHORT_SHA}'
      - '--project=${PROJECT_ID}'
    waitFor:
      - 'Prepare-Deployment-Directory'

# Substitutions for dynamic variables.
substitutions:
  _SERVICE_NAME: default

# Options for the build process.
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout configuration
timeout: '600s'  # 10 minutes